// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: HMI-7

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_DI1 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_DI2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_DI3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_DI4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_TR1 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_TR2 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_TR3 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_TR4 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_AI1 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_AI2 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_AI3 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_AI4 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -20);
    lv_obj_set_y(ui_Label1, -265);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "NORVI CONTROLLERS");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0BF719), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -374);
    lv_obj_set_y(ui_Label2, -190);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "DIGITAL INPUTS");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -323);
    lv_obj_set_y(ui_Label3, -35);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "TRANSISTOR OUTPUTS");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -367);
    lv_obj_set_y(ui_Label4, 140);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "ANALOG INPUTS");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 985);
    lv_obj_set_height(ui_Panel1, 107);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -118);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -304);
    lv_obj_set_y(ui_Label5, -8);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "DI1");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_DI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI1, 8);
    lv_obj_set_y(ui_DI1, 0);
    lv_obj_set_align(ui_DI1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI1, "0");
    lv_obj_set_style_text_color(ui_DI1, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -291);
    lv_obj_set_y(ui_Label7, -8);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "DI2");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_DI2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI2, 8);
    lv_obj_set_y(ui_DI2, 0);
    lv_obj_set_align(ui_DI2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI2, "0");
    lv_obj_set_style_text_color(ui_DI2, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -291);
    lv_obj_set_y(ui_Label6, -8);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "DI3");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_DI3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI3, 8);
    lv_obj_set_y(ui_DI3, 0);
    lv_obj_set_align(ui_DI3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI3, "0");
    lv_obj_set_style_text_color(ui_DI3, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -291);
    lv_obj_set_y(ui_Label8, -8);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "DI4");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_DI4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI4, 8);
    lv_obj_set_y(ui_DI4, 0);
    lv_obj_set_align(ui_DI4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI4, "0");
    lv_obj_set_style_text_color(ui_DI4, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 985);
    lv_obj_set_height(ui_Panel2, 107);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, 43);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -304);
    lv_obj_set_y(ui_Label9, -8);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "TR1");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TR1, 8);
    lv_obj_set_y(ui_TR1, 0);
    lv_obj_set_align(ui_TR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TR1, "OFF");
    lv_obj_set_style_text_color(ui_TR1, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -291);
    lv_obj_set_y(ui_Label10, -8);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "TR2");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TR2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TR2, 8);
    lv_obj_set_y(ui_TR2, 0);
    lv_obj_set_align(ui_TR2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TR2, "OFF");
    lv_obj_set_style_text_color(ui_TR2, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -291);
    lv_obj_set_y(ui_Label11, -8);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "TR3");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TR3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TR3, 8);
    lv_obj_set_y(ui_TR3, 0);
    lv_obj_set_align(ui_TR3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TR3, "OFF");
    lv_obj_set_style_text_color(ui_TR3, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -291);
    lv_obj_set_y(ui_Label12, -8);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "TR4");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TR4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TR4, 8);
    lv_obj_set_y(ui_TR4, 0);
    lv_obj_set_align(ui_TR4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TR4, "OFF");
    lv_obj_set_style_text_color(ui_TR4, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 985);
    lv_obj_set_height(ui_Panel3, 107);
    lv_obj_set_x(ui_Panel3, -1);
    lv_obj_set_y(ui_Panel3, 218);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -304);
    lv_obj_set_y(ui_Label13, -8);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "AI1");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AI1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_AI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI1, 8);
    lv_obj_set_y(ui_AI1, 0);
    lv_obj_set_align(ui_AI1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI1, "0.0");
    lv_obj_set_style_text_color(ui_AI1, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -291);
    lv_obj_set_y(ui_Label14, -8);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "AI2");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AI2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_AI2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI2, 8);
    lv_obj_set_y(ui_AI2, 0);
    lv_obj_set_align(ui_AI2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI2, "0.0");
    lv_obj_set_style_text_color(ui_AI2, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -291);
    lv_obj_set_y(ui_Label15, -8);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "AI3");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AI3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_AI3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI3, 8);
    lv_obj_set_y(ui_AI3, 0);
    lv_obj_set_align(ui_AI3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI3, "0.0");
    lv_obj_set_style_text_color(ui_AI3, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -291);
    lv_obj_set_y(ui_Label16, -8);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "AI4");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x1F4082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AI4 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_AI4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI4, 8);
    lv_obj_set_y(ui_AI4, 0);
    lv_obj_set_align(ui_AI4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI4, "0.0");
    lv_obj_set_style_text_color(ui_AI4, lv_color_hex(0xB51010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Panel1 = NULL;
    ui_Label5 = NULL;
    ui_DI1 = NULL;
    ui_Label7 = NULL;
    ui_DI2 = NULL;
    ui_Label6 = NULL;
    ui_DI3 = NULL;
    ui_Label8 = NULL;
    ui_DI4 = NULL;
    ui_Panel2 = NULL;
    ui_Label9 = NULL;
    ui_TR1 = NULL;
    ui_Label10 = NULL;
    ui_TR2 = NULL;
    ui_Label11 = NULL;
    ui_TR3 = NULL;
    ui_Label12 = NULL;
    ui_TR4 = NULL;
    ui_Panel3 = NULL;
    ui_Label13 = NULL;
    ui_AI1 = NULL;
    ui_Label14 = NULL;
    ui_AI2 = NULL;
    ui_Label15 = NULL;
    ui_AI3 = NULL;
    ui_Label16 = NULL;
    ui_AI4 = NULL;

}
