// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: HMI-7

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_DI1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_DI2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_DI3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_DI4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_TR1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TR2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_TR3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_TR4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_AI1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_AI2;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_AI3;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_AI4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

