// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: HMI-7-Complex_design

#ifndef _HMI_7_COMPLEX_DESIGN_UI_H
#define _HMI_7_COMPLEX_DESIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_256_empty_png);    // assets/256_empty.png
LV_IMG_DECLARE(ui_img_256_full_png);    // assets/256_full.png

// FONTS
LV_FONT_DECLARE(ui_font_Times40);
LV_FONT_DECLARE(ui_font_opensans40);
LV_FONT_DECLARE(ui_font_opensans34);
LV_FONT_DECLARE(ui_font_opensans26);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
