// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: HMI-7-Complex_design

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

 void setTransistorState(uint8_t output, bool state);

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_AI1;
extern lv_obj_t * ui_Panel1;
extern void ui_event_SWTR1(lv_event_t * e);
extern lv_obj_t * ui_SWTR1;
extern void ui_event_SWTR2(lv_event_t * e);
extern lv_obj_t * ui_SWTR2;
extern void ui_event_SWTR3(lv_event_t * e);
extern lv_obj_t * ui_SWTR3;
extern void ui_event_SWTR4(lv_event_t * e);
extern lv_obj_t * ui_SWTR4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_TR1;
extern lv_obj_t * ui_TR2;
extern lv_obj_t * ui_TR3;
extern lv_obj_t * ui_TR4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_AI2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_AI3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_AI4;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_DI1;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_DI2;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_DI3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_DI4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
