// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: HMI-7I-RS485

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Tempempty = NULL;
lv_obj_t * ui_Arc = NULL;
lv_obj_t * ui_Tempfull = NULL;
lv_obj_t * ui_Humidityvalue = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_temperaturevalue = NULL;
lv_obj_t * ui_Humidityzone = NULL;
lv_obj_t * ui_temperaturezone = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 6);
    lv_obj_set_y(ui_Label1, -252);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "NORVI CONTROLLERS");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_opensans40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tempempty = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Tempempty, &ui_img_temp_emp_png);
    lv_obj_set_width(ui_Tempempty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempempty, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tempempty, 237);
    lv_obj_set_y(ui_Tempempty, -5);
    lv_obj_set_align(ui_Tempempty, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tempempty, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Tempempty, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc, 470);
    lv_obj_set_height(ui_Arc, 469);
    lv_obj_set_x(ui_Arc, -158);
    lv_obj_set_y(ui_Arc, 9);
    lv_obj_set_align(ui_Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc, 0);
    lv_arc_set_bg_angles(ui_Arc, 290, 270);
    lv_obj_set_style_bg_img_src(ui_Arc, &ui_img_hum_emp_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc, &ui_img_hum_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Tempfull = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Tempfull, &ui_img_temp_full_png);
    lv_obj_set_width(ui_Tempfull, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tempfull, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tempfull, 236);
    lv_obj_set_y(ui_Tempfull, -5);
    lv_obj_set_align(ui_Tempfull, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tempfull, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Tempfull, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Humidityvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Humidityvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidityvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidityvalue, -156);
    lv_obj_set_y(ui_Humidityvalue, 11);
    lv_obj_set_align(ui_Humidityvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidityvalue, "0%");
    lv_obj_set_style_text_color(ui_Humidityvalue, lv_color_hex(0x57B4C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidityvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidityvalue, &ui_font_opensans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -152);
    lv_obj_set_y(ui_Label3, -50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Humidity");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_opensans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 178);
    lv_obj_set_y(ui_Label4, 233);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Temperature");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_opensans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperaturevalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperaturevalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperaturevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperaturevalue, 342);
    lv_obj_set_y(ui_temperaturevalue, 233);
    lv_obj_set_align(ui_temperaturevalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperaturevalue, "0.0 ");
    lv_obj_set_style_text_color(ui_temperaturevalue, lv_color_hex(0x57B4C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperaturevalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperaturevalue, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidityzone = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Humidityzone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidityzone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidityzone, -164);
    lv_obj_set_y(ui_Humidityzone, 65);
    lv_obj_set_align(ui_Humidityzone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidityzone, "Comfortable");
    lv_obj_set_style_text_color(ui_Humidityzone, lv_color_hex(0x00FF51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidityzone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidityzone, &ui_font_opensans26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperaturezone = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperaturezone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperaturezone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperaturezone, 439);
    lv_obj_set_y(ui_temperaturezone, 233);
    lv_obj_set_align(ui_temperaturezone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperaturezone, "Warm");
    lv_obj_set_style_text_color(ui_temperaturezone, lv_color_hex(0x00FF51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperaturezone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperaturezone, &ui_font_opensans26, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Tempempty = NULL;
    ui_Arc = NULL;
    ui_Tempfull = NULL;
    ui_Humidityvalue = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_temperaturevalue = NULL;
    ui_Humidityzone = NULL;
    ui_temperaturezone = NULL;

}
