// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: HMI-7-Complex_design

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_AI1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_SWTR1 = NULL;
lv_obj_t * ui_SWTR2 = NULL;
lv_obj_t * ui_SWTR3 = NULL;
lv_obj_t * ui_SWTR4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_TR1 = NULL;
lv_obj_t * ui_TR2 = NULL;
lv_obj_t * ui_TR3 = NULL;
lv_obj_t * ui_TR4 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Arc2 = NULL;
lv_obj_t * ui_AI2 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Arc3 = NULL;
lv_obj_t * ui_AI3 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Arc4 = NULL;
lv_obj_t * ui_AI4 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_DI1 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_DI2 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_DI3 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_DI4 = NULL;
// event funtions
void ui_event_SWTR1(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) {
        lv_obj_t * target = lv_event_get_target(e);
        bool state = lv_obj_has_state(target, LV_STATE_CHECKED);
        setTransistorState(1, state);
        lv_label_set_text(ui_TR1, state ? "ON" : "OFF");
    }
}


void ui_event_SWTR2(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) {
        lv_obj_t * target = lv_event_get_target(e);
        bool state = lv_obj_has_state(target, LV_STATE_CHECKED);
        setTransistorState(2, state);
        lv_label_set_text(ui_TR2, state ? "ON" : "OFF");
    }
}

void ui_event_SWTR3(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) {
        lv_obj_t * target = lv_event_get_target(e);
        bool state = lv_obj_has_state(target, LV_STATE_CHECKED);
        setTransistorState(3, state);
        lv_label_set_text(ui_TR3, state ? "ON" : "OFF");
    }
}

void ui_event_SWTR4(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) {
        lv_obj_t * target = lv_event_get_target(e);
        bool state = lv_obj_has_state(target, LV_STATE_CHECKED);
        setTransistorState(4, state);
        lv_label_set_text(ui_TR4, state ? "ON" : "OFF");
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_width(ui_Arc1, 239);
    lv_obj_set_height(ui_Arc1, 238);
    lv_obj_set_x(ui_Arc1, -351);
    lv_obj_set_y(ui_Arc1, -97);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Arc1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_range(ui_Arc1, 0, 20);
    lv_arc_set_value(ui_Arc1, 0);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x00CCFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 12);
    lv_obj_set_y(ui_Label1, -265);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "NORVI CONTROLLERS");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Times40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AI1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI1, -354);
    lv_obj_set_y(ui_AI1, -114);
    lv_obj_set_align(ui_AI1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI1, "0.0");
    lv_obj_set_style_text_color(ui_AI1, lv_color_hex(0xE8410D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 133);
    lv_obj_set_height(ui_Panel1, 265);
    lv_obj_set_x(ui_Panel1, 413);
    lv_obj_set_y(ui_Panel1, -87);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWTR1 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_SWTR1, 100);
    lv_obj_set_height(ui_SWTR1, 45);
    lv_obj_set_x(ui_SWTR1, 390);
    lv_obj_set_y(ui_SWTR1, -136);
    lv_obj_set_align(ui_SWTR1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SWTR1, lv_color_hex(0xA29999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SWTR1, lv_color_hex(0x696666), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SWTR2 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_SWTR2, 100);
    lv_obj_set_height(ui_SWTR2, 45);
    lv_obj_set_x(ui_SWTR2, 390);
    lv_obj_set_y(ui_SWTR2, -28);
    lv_obj_set_align(ui_SWTR2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SWTR2, lv_color_hex(0xA29999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SWTR2, lv_color_hex(0x696666), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SWTR3 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_SWTR3, 100);
    lv_obj_set_height(ui_SWTR3, 45);
    lv_obj_set_x(ui_SWTR3, 387);
    lv_obj_set_y(ui_SWTR3, 73);
    lv_obj_set_align(ui_SWTR3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SWTR3, lv_color_hex(0xA29999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SWTR3, lv_color_hex(0x696666), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SWTR4 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_SWTR4, 100);
    lv_obj_set_height(ui_SWTR4, 45);
    lv_obj_set_x(ui_SWTR4, 384);
    lv_obj_set_y(ui_SWTR4, 182);
    lv_obj_set_align(ui_SWTR4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SWTR4, lv_color_hex(0xA29999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SWTR4, lv_color_hex(0x696666), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWTR4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 93);
    lv_obj_set_height(ui_Panel2, 281);
    lv_obj_set_x(ui_Panel2, 276);
    lv_obj_set_y(ui_Panel2, -68);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR1, 75);
    lv_obj_set_height(ui_TR1, 50);
    lv_obj_set_x(ui_TR1, 22);
    lv_obj_set_y(ui_TR1, 29);
    lv_obj_set_align(ui_TR1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TR1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TR1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_TR1, "OFF");
    lv_obj_set_style_text_color(ui_TR1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR2, 75);
    lv_obj_set_height(ui_TR2, 50);
    lv_obj_set_x(ui_TR2, 22);
    lv_obj_set_y(ui_TR2, 29);
    lv_obj_set_align(ui_TR2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TR2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TR2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_TR2, "OFF");
    lv_obj_set_style_text_color(ui_TR2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR3, 75);
    lv_obj_set_height(ui_TR3, 50);
    lv_obj_set_x(ui_TR3, 22);
    lv_obj_set_y(ui_TR3, 29);
    lv_obj_set_align(ui_TR3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TR3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TR3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_TR3, "OFF");
    lv_obj_set_style_text_color(ui_TR3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TR4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TR4, 75);
    lv_obj_set_height(ui_TR4, 50);
    lv_obj_set_x(ui_TR4, 22);
    lv_obj_set_y(ui_TR4, 29);
    lv_obj_set_align(ui_TR4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TR4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TR4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_TR4, "OFF");
    lv_obj_set_style_text_color(ui_TR4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TR4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 93);
    lv_obj_set_height(ui_Panel3, 281);
    lv_obj_set_x(ui_Panel3, 171);
    lv_obj_set_y(ui_Panel3, -68);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label7, 75);
    lv_obj_set_height(ui_Label7, 50);
    lv_obj_set_x(ui_Label7, 22);
    lv_obj_set_y(ui_Label7, 29);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "TR1");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label8, 75);
    lv_obj_set_height(ui_Label8, 50);
    lv_obj_set_x(ui_Label8, 22);
    lv_obj_set_y(ui_Label8, 29);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "TR2");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label9, 75);
    lv_obj_set_height(ui_Label9, 50);
    lv_obj_set_x(ui_Label9, 22);
    lv_obj_set_y(ui_Label9, 29);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "TR3");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label10, 75);
    lv_obj_set_height(ui_Label10, 50);
    lv_obj_set_x(ui_Label10, 22);
    lv_obj_set_y(ui_Label10, 29);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "TR4");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_Screen1);
    lv_obj_clear_flag(ui_Arc2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_width(ui_Arc2, 235);
    lv_obj_set_height(ui_Arc2, 238);
    lv_obj_set_x(ui_Arc2, -60);
    lv_obj_set_y(ui_Arc2, -104);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Arc2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_range(ui_Arc2, 0, 20);
    lv_arc_set_value(ui_Arc2, 0);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x00CCFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AI2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AI2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI2, -59);
    lv_obj_set_y(ui_AI2, -114);
    lv_obj_set_align(ui_AI2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI2, "0.0");
    lv_obj_set_style_text_color(ui_AI2, lv_color_hex(0xE8410D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -354);
    lv_obj_set_y(ui_Label12, -65);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "A1");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -59);
    lv_obj_set_y(ui_Label13, -65);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "A2");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_Screen1);
    lv_obj_clear_flag(ui_Arc3, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_width(ui_Arc3, 235);
    lv_obj_set_height(ui_Arc3, 238);
    lv_obj_set_x(ui_Arc3, -351);
    lv_obj_set_y(ui_Arc3, 158);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Arc3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_range(ui_Arc3, 0, 20);
    lv_arc_set_value(ui_Arc3, 0);
    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc3, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0x00CCFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AI3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AI3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI3, -354);
    lv_obj_set_y(ui_AI3, 143);
    lv_obj_set_align(ui_AI3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI3, "0.0");
    lv_obj_set_style_text_color(ui_AI3, lv_color_hex(0xE8410D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI3, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -354);
    lv_obj_set_y(ui_Label15, 197);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "A3");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc4 = lv_arc_create(ui_Screen1);
    lv_obj_clear_flag(ui_Arc4, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_width(ui_Arc4, 235);
    lv_obj_set_height(ui_Arc4, 238);
    lv_obj_set_x(ui_Arc4, -60);
    lv_obj_set_y(ui_Arc4, 154);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Arc4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_range(ui_Arc4, 0, 20);
    lv_arc_set_value(ui_Arc4, 0);
    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc4, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0x00CCFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AI4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AI4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AI4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AI4, -59);
    lv_obj_set_y(ui_AI4, 145);
    lv_obj_set_align(ui_AI4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AI4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AI4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_AI4, "0.0");
    lv_obj_set_style_text_color(ui_AI4, lv_color_hex(0xE8410D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AI4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AI4, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -61);
    lv_obj_set_y(ui_Label17, 194);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "A4");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 85);
    lv_obj_set_height(ui_Panel4, 94);
    lv_obj_set_x(ui_Panel4, 147);
    lv_obj_set_y(ui_Panel4, 178);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 159);
    lv_obj_set_y(ui_Label18, 136);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "DI1");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_DI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI1, 144);
    lv_obj_set_y(ui_DI1, 237);
    lv_obj_set_align(ui_DI1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI1, "0");
    lv_obj_set_style_text_color(ui_DI1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 85);
    lv_obj_set_height(ui_Panel5, 94);
    lv_obj_set_x(ui_Panel5, 247);
    lv_obj_set_y(ui_Panel5, 178);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 159);
    lv_obj_set_y(ui_Label20, 136);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "DI2");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_DI2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI2, 144);
    lv_obj_set_y(ui_DI2, 237);
    lv_obj_set_align(ui_DI2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI2, "0");
    lv_obj_set_style_text_color(ui_DI2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 85);
    lv_obj_set_height(ui_Panel6, 94);
    lv_obj_set_x(ui_Panel6, 346);
    lv_obj_set_y(ui_Panel6, 178);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 159);
    lv_obj_set_y(ui_Label22, 136);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "DI3");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI3 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_DI3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI3, 144);
    lv_obj_set_y(ui_DI3, 237);
    lv_obj_set_align(ui_DI3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI3, "0");
    lv_obj_set_style_text_color(ui_DI3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 85);
    lv_obj_set_height(ui_Panel7, 94);
    lv_obj_set_x(ui_Panel7, 442);
    lv_obj_set_y(ui_Panel7, 178);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 159);
    lv_obj_set_y(ui_Label24, 136);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "DI4");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x0401F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DI4 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_DI4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DI4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DI4, 144);
    lv_obj_set_y(ui_DI4, 237);
    lv_obj_set_align(ui_DI4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DI4, "0");
    lv_obj_set_style_text_color(ui_DI4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DI4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DI4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SWTR1, ui_event_SWTR1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SWTR2, ui_event_SWTR2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SWTR3, ui_event_SWTR3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SWTR4, ui_event_SWTR4, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Arc1 = NULL;
    ui_Label1 = NULL;
    ui_AI1 = NULL;
    ui_Panel1 = NULL;
    ui_SWTR1 = NULL;
    ui_SWTR2 = NULL;
    ui_SWTR3 = NULL;
    ui_SWTR4 = NULL;
    ui_Panel2 = NULL;
    ui_TR1 = NULL;
    ui_TR2 = NULL;
    ui_TR3 = NULL;
    ui_TR4 = NULL;
    ui_Panel3 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Arc2 = NULL;
    ui_AI2 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Arc3 = NULL;
    ui_AI3 = NULL;
    ui_Label15 = NULL;
    ui_Arc4 = NULL;
    ui_AI4 = NULL;
    ui_Label17 = NULL;
    ui_Panel4 = NULL;
    ui_Label18 = NULL;
    ui_DI1 = NULL;
    ui_Panel5 = NULL;
    ui_Label20 = NULL;
    ui_DI2 = NULL;
    ui_Panel6 = NULL;
    ui_Label22 = NULL;
    ui_DI3 = NULL;
    ui_Panel7 = NULL;
    ui_Label24 = NULL;
    ui_DI4 = NULL;

}
